"""Fovea's public event API."""

from fovea.events import (
    Blink,
    CalibrationCue,
    CalibrationDone,
    CalibrationWarning,
    Diagnostics,
    DoubleBlink,
    Dwell,
    DwellProgress,
    Eye,
    Fixation,
    FoveaEvent,
    GazePoint,
    GazeTestDone,
    GazeTestPoint,
    Gesture,
    GesturePhase,
    LongBlink,
    Manipulation,
    Saccade,
    TargetEnter,
    TargetLeave,
    TrackingState,
    TrackingStatus,
    Wink,
)
from fovea.interfaces import EventSink, EventSource
from fovea.webcam import (
    GazeEngine,
    GazeSettings,
    LandmarkBackend,
    LandmarkObservation,
    TargetRect,
    TargetTracker,
    WebcamEventSource,
)

__all__ = [
    "Blink",
    "CalibrationCue",
    "CalibrationDone",
    "CalibrationWarning",
    "Diagnostics",
    "DoubleBlink",
    "Dwell",
    "DwellProgress",
    "EventSink",
    "EventSource",
    "Eye",
    "Fixation",
    "FoveaEvent",
    "GazeEngine",
    "GazePoint",
    "GazeSettings",
    "GazeTestDone",
    "GazeTestPoint",
    "Gesture",
    "GesturePhase",
    "LandmarkBackend",
    "LandmarkObservation",
    "LongBlink",
    "Manipulation",
    "Saccade",
    "TargetEnter",
    "TargetLeave",
    "TargetRect",
    "TargetTracker",
    "TrackingState",
    "TrackingStatus",
    "WebcamEventSource",
    "Wink",
]

__version__ = "0.1.0"
